language: node_js
node_js:
- 8.4.0
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: TTbIS37e+1RkXtj8i5Ks6QA8+5UWnwyJfALecsSNzBZJHuDny+I/s+zznb5BkV6fBpNdyGD0dRX0KTjzjj/xZG19qB9gSxKb2v+VLGosuxAGC/eH8f3jyrJb0F73SduSKk6tLm8jQOk9YF7jaQ40FokYenfPhVPu/vetZgdj6UNz6nVouyD/8h/FUbz0UKdnfF+8ywUE33IXmU9+H9+1hXot1KZJtuD9EIfkdPra5KD5MjoFVcTtlSBD3BDjYu9vZhov1CVrHxkAW2uUcMf168Wpwhq7yR4jhaAy+V+apNigJVK4lDSTOsuliYxsRnIVQ2NXKp0IzAoVT45MqjiAeCUExxMJ9U2zHXy/l0mEbX/hpWUg4YCm+4qjWHlQdYUvmUVhbr9HktF2543Ac+NHEWBj/KyoaAPVZ9XWlBzv4wSaQ2WeWcESM5r86ylG296ZcNHpVC/e8N+c990074l2zF7xLe74u9iGLJ7K0YZjt/M94qwuR2MV322hitjuXjLi0ic7WEfNcH1pbZb3Fwladj7kq/5QinNCcX8A1IafAG+sYb3pnHJo4/1MnerL8s+39Lbn7lFDAWQDByfnLnc5Gitz4F/AZk7ZoIA1d08EfQhWNRTaIr6jDWeWyZfcVfqh1fkorWfWbTdIoEQi9W6JMpX11ltpGjIBB9M4Z7DqmJw=
