language: node_js
node_js:
- 8.4.0
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: E2+sF5ocrmaM19HzqygdK9F1GqB7bqBFzNEeZQkjmENjADMjHFXOkmmgWHMDxzVukAKvVxbdo5mpBbPl8sp1RdPWWKJqviAEpPcaRBUGLsZDJftHNajUF6lqvaZ2sLLOkiILfgy4yzr/nLr5o80cqkfKtyfoVRPcmFUBf4ihS9u6X1CsH6K0BZRlPtBckI2LOag44kLAIINXOPVb5B6bm4GFWZcCiJgyyDDjGHRvMM8HKTmFiK8YNiJvBN6QD2PFYl/ILm1Td4Z5xWDUyD2v+N8ldd5pYrwJWAIAcKb49JMUy4shww7onE5rm5RwXYPjla33I8nxJAATkN0N56UymbnevEDQQZRkmQ5yisAdzUwQSeWmWkwWS0K3aZ9jQY5jNIW9XFhkNASlYwChPklsf9VnhHT42Q814d8uxKViH7/gIiwfliKOCTUvuwVGOfhtOfh2MPQf7I4kXo3wj+Cj44JmJfli2wb8IvsNcRBLFGq3VnAXEMlCs/K88+uWj6MpP9LMsza8JFQfnW3KZXu+MaiHAV0zv8qcc9FrnB6MI/3eY21YeE+CV0hl5eLSEY/Xd4dSmW6NQdTBK+XkKCkNxzzoSqTzouLw5Kde+t//hUbKgER+im/o0UBEjje0ZuwBG8F07CdENka06aJBhEkbSDG1rQJkrTRVpFnfZCTOh4E=
