language: node_js
node_js:
- 8.4.0
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: VO5Fma5Zr8Ovgj4mv9MyUWu9j6keDU0vGvjXBrzwbn31x59FXGdMVX0sbzR9JgQ5nKOVgXTyiysRzRjuBrjL6phJ1uQEMo+BJFeI/xGBy3HIiEWEL595uGEEy1tZuiXpFmdzvdVuNwJ9dJs7fevcVnfYNRLwzsAxSoEdl3RNIoMAEEgdVW7OZOqPDC7yQtYVfnHSx3UmilelcYafaxgO2UXTsFslJqbHkH7yfqOPLo3CTDFZxM4diey/WGJQdSpFHO6apq8ZhwzGptvCmdoPuAsptdBJTkMD4V+vbjOtvZ82ZbljiltFPbC4pyVHth9ecmEwf1r7zQRY/S40giCD4J+fpX16fQ1UMeuaIvPvR9nHRoPkPdcUHIMU1a9oQgv4vlt7VBMZXS4xd0uZ7TeWUKwgQ2kEzoaiDkhsb/1JW3YKExKV3fFvXQywvHak0d+jyt+QueXZRBYpH5tsuGdB+pVCKKDwE0cVf4pih40lHo3uG4YV9EFdsG/3VratfEfitcs/a+3xMfh2W044Hv9x+akpgGmoLYbQ5XT1tnxemcBwGQga24io1fHS7+t1ZwhdOd5AI2N8kspz2FsyGSHynHP4LC9U/lLJtgRmWrVVoWEtfl0K8WevygfDP9cB5W+J+f4pBxnGSNQZr32LtAEasYp/nIEJGLFdAf9zLIAj7FU=
